name: main2

on: 
  push:
    paths: 
      - .github/workflows/main2.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          ./make_android_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: plugin_lua54-android
          path: ./build/plugin_lua54/
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd build
          ./make_ios_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: plugin_lua54-ios
          path: ./build/plugin_lua54/
  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd build
          ./make_osx_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: plugin_lua54-macos
          path: ./build/plugin_lua54/
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          cd build
          .\make_win_lua54.bat
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: plugin_lua54-windows
          path: ./build/plugin_lua54/
